### ISSUE TITLE
On the driving of tc358749xbg

### ISSUE THREAD

**Issue by blikvm** [6by9/raspi_tc358743#2]
Hello, I'm one of the main manufacturers of HDMI to CSI adapter board. The price of tc358743 has gone up too high in the last half year, but I didn't want the price of terminal board to go up, so I found another chip tc358749 of the same kind, but my software level is limited, and I won't drive it in raspberry. Can you help me with this

**Comment by 6by9** [comment]
This is the wrong repo to be asking for support as the program is deprecated (noted in the README).
I've created https://github.com/raspberrypi/linux/issues/4235 to continue the discussion.

All support for the TC358743 is via the [Linux kernel driver](https://github.com/raspberrypi/linux/blob/rpi-5.10.y/drivers/media/i2c/tc358743.c), loaded via ```dtoverlay=tc358743```.

I wasn't aware of the TC358749 until now. Reading the [product spec](https://toshiba.semicon-storage.com/content/dam/toshiba-ss/ncsa/en_us/docs/product-brief/assp/13G04_TC358749_ProdBrief.pdf)
> The Toshiba  TC358749XBG is a follow on part to the Toshiba TC358743XBG adding video de-interlacing, video scaling,  video format conversion and MIPI SLIMbus audio support.

The deinterlacing and scaling is likely to need new register setup. The 743 already did format conversion providing that it is the same.

Just doing a Google has brought up https://github.com/54shady/qop_kernel/blob/master/drivers/media/i2c/tc35874x.c as a driver for '743 and '749. Looking at https://github.com/54shady/qop_kernel/commit/2e3c43155bc6ff790e27ed19f2501c95553bba1e it's a rename of the mainline '743 driver with a massive rename, and then [a small amount of fixup for the '749](https://github.com/54shady/qop_kernel/commits/master/drivers/media/i2c/tc35874x.c). 

I'm happy to look at adding support for the '749 to the kernel driver, but have no hardware to test with, and no datasheet. I believe we do still have a relationship with Toshiba so may be able to get the datasheet.

Support will NOT be added to the firmware for '749, therefore the use of raspivid etc with it is not going to be possible.

**Comment by 6by9** [comment]
Closing - please use https://github.com/raspberrypi/linux/issues/4235.

**Comment by blikvm** [comment]
I use tc358743 chip as the adapter board manufacturer. In the new board, I have repaired the sound and used four channels, which can support 1080p 60fps. In the preparation process, I found that the price of tc358743 chip was too high, so I wanted to use tc358749 instead. You see what you need, I can give you the corresponding equipment.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "6by9/raspi_tc358743"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月25日(星期四) 下午5:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [6by9/raspi_tc358743] On the driving of tc358749xbg (#2)





 
Closed #2.

**Comment by blikvm** [comment]
I have 749's product datasheet, but you don't have enough space to send prompt in this email. Do you have any other email? I'll send you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "6by9/raspi_tc358743"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月25日(星期四) 下午5:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [6by9/raspi_tc358743] On the driving of tc358749xbg (#2)





 
This is the wrong repo to be asking for support as the program is deprecated (noted in the README).
 I've created raspberrypi/linux#4235 to continue the discussion.
 
All support for the TC358743 is via the Linux kernel driver, loaded via dtoverlay=tc358743.
 
I wasn't aware of the TC358749 until now. Reading the product spec
  
The Toshiba  TC358749XBG is a follow on part to the Toshiba TC358743XBG adding video de-interlacing, video scaling,  video format conversion and MIPI SLIMbus audio support.
  
The deinterlacing and scaling is likely to need new register setup. The 743 already did format conversion providing that it is the same.
 
Just doing a Google has brought up https://github.com/54shady/qop_kernel/blob/master/drivers/media/i2c/tc35874x.c as a driver for '743 and '749. Looking at ***@***.*** it's a rename of the mainline '743 driver with a massive rename, and then a small amount of fixup for the '749.
 
I'm happy to look at adding support for the '749 to the kernel driver, but have no hardware to test with, and no datasheet. I believe we do still have a relationship with Toshiba so may be able to get the datasheet.
 
Support will NOT be added to the firmware for '749, therefore the use of raspivid etc with it is not going to be possible.

**Comment by 6by9** [comment]
If the datasheet isn't under NDA, then feel free to email it to me as dave.stevenson@raspberrypi.com.
